# --- Error test cases ---

# Create error1.txt - First line format is invalid (missing characters)
cat > ./maps/error1.txt << 'EOF'
4.o
....
.o..
....
....
EOF

# Create error2.txt - First line format is invalid (non-numeric row count)
cat > ./maps/error2.txt << 'EOF'
a.ox
....
.o..
....
....
EOF

# Create error3.txt - Non-printable character in the first line
cat > ./maps/error3.txt << 'EOF'
4.\01x
....
.o..
....
....
EOF

# Create error4.txt - Duplicate characters in the first line
cat > ./maps/error4.txt << 'EOF'
4.oo
....
.o..
....
....
EOF

# Create error5.txt - Wrong number of rows (fewer than specified)
cat > ./maps/error5.txt << 'EOF'
5.ox
....
.o..
....
EOF

# Create error6.txt - Wrong number of rows (more than specified)
cat > ./maps/error6.txt << 'EOF'
3.ox
....
.o..
....
....
EOF

# Create error7.txt - Inconsistent row lengths
cat > ./maps/error7.txt << 'EOF'
4.ox
....
.o...
....
....
EOF

# Create error8.txt - Invalid characters in the map
cat > ./maps/error8.txt << 'EOF'
4.ox
....
.o..
.a..
....
EOF

# Create error9.txt - Missing newline after first line
cat > ./maps/error9.txt << 'EOF'
4.ox....
.o..
....
....
EOF

# Create error10.txt - Empty file
cat > ./maps/error10.txt << 'EOF'
EOF

# Create error11.txt - First line has newline but no content
cat > ./maps/error11.txt << 'EOF'

....
.o..
....
....
EOF

echo "All test files have been created successfully."